apiVersion: v1
kind: Secret
metadata:
  name: flipkart-secrets
  namespace: flipkart-prod
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "FlipkartSecurePassword2026!"
  JWT_SECRET: "ProductionSecretKeyForFlipkartEnterpriseSigningTokensMinimum256BitsLong"
